xataio/mdx-docs

- 040-Typescript-SDK/100-aggregate.mdx
I'm going to adjust the PR to make this kind of thing a hard error, rather than a warning.
> Missing slug on aggregate page

- 030-Concepts/030-data-model.mdx
I merged the docs before having the SDK support and blogpost and this can be confusing for some users (one already asked on Discord). This adds an explanatory note about what to expect.
https://xata-hq.slack.com/archives/C04SG0TEQ5B/p1689187673406809
Closes #
The following changes are committed in this pull request:
*
*
--------------------------------------------------
**Release**:
> Add note on backwards links

- 020-Getting-started/070-nextjs.mdx
- 040-Typescript-SDK/040-get.mdx
> Doc typo fixes

- 050-Python-SDK/040-namespace-reference.mdx
Fix minor typo on the python SDK nav
Closes #
-
---
---
**Release**:
> Correct typo on 040-namespace-reference.mdx (#47)

- 030-Concepts/030-data-model.mdx
> Add python snippet for revlinks

- 040-Typescript-SDK/130-ask.mdx
We launched the new "chat" functionality for our ask endpoint, this is updates to our ask guide
> Updated with text and examples for the chat feature, minor adjustments to original text

- 020-Getting-started/070-nextjs.mdx
While testing the getting started guide for Next.js I've noticed some small issues.
> Minimal fixes for the next.js guide

- 020-Getting-started/080-astro.mdx
Some of the same fixes as in #55 but for the Astro one.
Interestingly Astro  doesn't have the serializable gotchas :)
> Small fixes to the Astro guide

- 020-Getting-started/040-workflow.mdx
Add missing create statement (`xata branch branchname` does not work any more, requires create)
> add missing create

- 040-SDK/101-get.mdx
- 040-SDK/102-create.mdx
- 040-SDK/103-update.mdx
- 040-SDK/104-delete.mdx
- 040-SDK/115-filtering.mdx
- 040-SDK/121-summarize.mdx
Adds SQL snippets to the Getting Records docs, should be released with https://github.com/xataio/mdx-docs/pull/44
Replaces: https://github.com/xataio/mdx-docs/pull/46
> SQL Snippets in new SDK section

- 040-SDK/010-TypeScript/010-overview.mdx
Documentation of SDK helper methods for custom types.
> add helper methods reference

- .github/workflows/preview.yml
Same as: https://github.com/xataio/mdx-blog/pull/81
> One concurrent build at a time

- 040-SDK/020-Python/020-examples.mdx
> Add Pagination example to Python SDK

- 060-Rest-API/020-contexts.mdx
Linking the SQL OpenAPI spec in the OAS section.
> Link SQL OAS

- 040-SDK/010-TypeScript/010-overview.mdx
Documents a common serialization pattern that happens a lot in Next JS with client-side components.
> TypeScript serialization example

- 030-Concepts/075-file-attachments.mdx
This documents the `transformImage` function from the client.
> Client side image transformation docs

- 030-Concepts/075-file-attachments.mdx
- snippet for transform
- adjusted code to new API design
> File attachment fixes for python sdk

- 040-SDK/115-filtering.mdx
Closes #
-
---
---
**Release**:
> Add missing fixes to queries with `LIKE`

- 040-SDK/150-file-attachments.mdx
- 040-SDK/160-image-transformations.mdx
Closes #
-
---
---
**Release**:
> small typo fix

- .github/workflows/preview.yml
- Add an alias for the PR xata-docs-pr-105.vercel.app
- Show the comment when triggering the deploy with the inspect url
- Update the comment when the deploy has finished
> Update workflow to have preview on PRs

- 040-SDK/100-sql-access.mdx
Closes #
-
---
---
**Release**:
> Publish SQL access documentation page

- 040-SDK/160-image-transformations.mdx
> Update docs for download transformation

- 040-SDK/160-image-transformations.mdx
Closes #
-
---
---
**Release**:
> Remove download example

- 020-Getting-started/040-workflow.mdx
- 030-Concepts/060-data-copying.mdx
- 070-Integrations/030-github.mdx
Clarify that file attachments are not copied to Preview branches
> Note for workflow with file columns

- 030-Concepts/075-file-attachments.mdx
- 040-SDK/150-file-attachments.mdx
Closes #
Document append and delete items from file arrays. Added examples for both Record APIs and File binary APIs
-
---
---
**Release**:
> Document append and delete items from file arrays

- 060-Rest-API/020-contexts.mdx
the SQL spec has moved in the `workspace` spec.
**Release**:
> Remove separate SQL spec

- 040-SDK/101-get.mdx
- 040-SDK/103-update.mdx
Fix python snippets for get and update record.
> fix python get and update record

- 020-Getting-started/090-available-regions.mdx
list all available regions on Xata and code snippet how to retrieve the list from code.
**Release**:
> Add page listing the available regions

- 040-SDK/121-summarize.mdx
Explain how to retrieve the total record count of a table in an efficient way.
**Release**:
> Get records count of a table

- 040-SDK/130-transaction.mdx
Closes #
- Update docs based on feedback from discord regarding [Python snippet](https://discord.com/channels/996791218879086662/1080566100003131543/1157223155438452817)
---
---
**Release**:
>  update python snippet

- 030-Concepts/080-pricing.mdx
- 040-SDK/111-search.mdx
- 040-SDK/120-aggregate.mdx
- 040-SDK/130-transaction.mdx
- 060-Rest-API/040-limits.mdx
Closes #
- Remove mention of units
- Update timeouts
- Remove ticks
---
---
**Release**:
> Updates for pricing

- 020-Getting-started/040-workflow.mdx
- 070-Integrations/070-vercel.mdx
Adds some more clarity around the order of operations for applying the vercel integration. This came as feedback from a conversation @kostasb and I were having with a user over Discord.
> Troubleshooting for vercel integration

- 030-Concepts/050-schema.mdx
- 040-SDK/020-Python/020-examples.mdx
Add documentation reference and example about updating schema from the Python SDK.
Clarifies [Discord](https://discord.com/channels/996791218879086662/1166252170283339796/1166252170283339796) question.
> Add python sdk schema edit references

- .github/workflows/deploy.yml
Same as: https://github.com/xataio/mdx-blog/pull/153
> Deploy Vercel website on push to main branch

- 030-Concepts/030-data-model.mdx
- 040-SDK/101-get.mdx
- package-lock.json
Examples for managing JOINs and many-to-many with SQL and Kysely.
> kysely join and many-to-many section

- 040-SDK/030-Go/010-overview.mdx
- 040-SDK/101-get.mdx
- 040-SDK/111-search.mdx
- 040-SDK/121-summarize.mdx
More usage examples for the Go SDK and added a know limitation of the SDK
**Release**:
> Xata Go - more code snippets

- 030-Concepts/030-data-model.mdx
> Mark object type as unsupported

- 080-Recipes/010-CSV-data/020-import-csv-data-CLI.mdx
Closes #187
Brief example for creating links with CLI csv import.
> csv links ref

- 020-Getting-started/030-Framework-starter-guides/010-astro.mdx
- 020-Getting-started/030-Framework-starter-guides/020-nextjs.mdx
- 020-Getting-started/030-Framework-starter-guides/030-nuxt.mdx
- 020-Getting-started/030-Framework-starter-guides/040-remix.mdx
- 020-Getting-started/030-Framework-starter-guides/050-sveltekit.mdx
- 020-Getting-started/030-Framework-starter-guides/060-solidstart.mdx
Apply changes from https://github.com/xataio/examples/pull/571 for search response breaking change.
> Update starters for search breaking change

- 040-SDK/115-filtering.mdx
Closes #
Adds two more complex examples to highlight how to combine filter operators.
**Release**:
> Add filtering examples

- 030-Concepts/080-pricing.mdx
> Fix typos in pricing docs

- 030-Concepts/080-pricing.mdx
Closes #
- Clarification that Ai and storage are per workspace and not per branch
---
**Release**:
> Add workspace mention

- 030-Concepts/030-data-model.mdx
- 030-Concepts/075-file-attachments.mdx
- 040-SDK/150-file-attachments.mdx
Closes #
Adds documentation for the new upload url field available on the file object.
---
Backend support was deployed to PROD.
SDK support was released.
---
**Release**:
> Document the new file upload url field

- 030-Concepts/075-file-attachments.mdx
- 040-SDK/101-get.mdx
- 040-SDK/150-file-attachments.mdx
Closes #
follow up of #197 
**Release**:
> Add Go snippets for file attachments

- 030-Concepts/075-file-attachments.mdx
Fixes linting errors introduced in https://github.com/xataio/mdx-docs/pull/204
> fix linting in file attachments

- 020-Getting-started/030-Framework-starter-guides/040-remix.mdx
The changes here were already reviewed in https://github.com/xataio/examples/pull/607
> remix v2 starter updates

- 020-Getting-started/030-Framework-starter-guides/010-astro.mdx
- 020-Getting-started/030-Framework-starter-guides/020-nextjs.mdx
- 020-Getting-started/030-Framework-starter-guides/030-nuxt.mdx
- 020-Getting-started/030-Framework-starter-guides/040-remix.mdx
- 020-Getting-started/030-Framework-starter-guides/050-sveltekit.mdx
- 020-Getting-started/030-Framework-starter-guides/060-solidstart.mdx
Adds Powershell examples for commands that work slightly different on Windows
> add powershell tabs

- 040-SDK/030-Go/010-overview.mdx
> Explain env vars in xata-go

- CODE_OF_CONDUCT.md
- code_of_conduct.md
Closes #
- ***
---
---
**Release**:
> Add standard conduct doc for contrib guide

- 040-SDK/111-search.mdx
- 040-SDK/111-vector-search.mdx
Closes #52
- **Adds totalCount** - Total count is included in responses fro query searches. This PR adds the definition to the SDK docs
---
---
**Release**:
> Add totalCount

- 040-SDK/102-create.mdx
- 040-SDK/130-transaction.mdx
code snippets and more for https://github.com/xataio/mdx-docs/pull/224
> Fixes for #224

- 040-SDK/130-transaction.mdx
fix for https://github.com/xataio/mdx-docs/pull/225
> Remove trailing s from method

- 040-SDK/101-get.mdx
- 040-SDK/103-update.mdx
Align property names in some code snippets and remove the last object type address column reference.
> Minor fixes code and object

- .github/workflows/prettier-fixes.yml
- 030-Concepts/010-serverless-data-platform.mdx
Closes #
Copies the github action from our frontend codebase which automatically corrects prettier mistakes with an extra commit.
> [Tech] Auto prettier fixes

- 040-SDK/111-search.mdx
- 040-SDK/111-vector-search.mdx
Closes https://github.com/xataio/mdx-docs/issues/235
> Search eventual consistency edits

- 040-SDK/130-transaction.mdx
Closes #
- ***
---
---
**Release**:
> remove non entry

- 040-SDK/130-transaction.mdx
as titled, PR: https://github.com/xataio/mdx-docs/pull/240
> Fix code snippets for PR 240

- 030-Concepts/030-data-model.mdx
- 040-SDK/102-create.mdx
- 060-Rest-API/020-contexts.mdx
- 100-Resources/100-Support.mdx
Closes #247
- **Fixes some links in our docs**  - Identified in this [spreadsheet](https://docs.google.com/spreadsheets/d/1uU_AZjjy6ps5ogWfXah6ZMtMP12vlgyv7v30rVJqKpE/edit?usp=sharing)
---
---
**Release**:
> Update broken links

- 040-SDK/104-delete.mdx
- 040-SDK/130-transaction.mdx
Closes #25 #42 
- **Adding examples and timeout note** - Adding examples to the transactions doc and clarifying language. Also including the timeout that occurs with bulk deletes mentioned in [Discord](https://discord.com/channels/996791218879086662/1075788625586966637/threads/1201746322370342952)
---
---
**Release**:
> Update transactions doc to include bulk delete and timeouts

- 040-SDK/111-search.mdx
- 040-SDK/150-file-attachments.mdx
Add reference for file metadata in Search
Closes https://github.com/xataio/mdx-docs/issues/258
> search results with file metadata

- 040-SDK/130-transaction.mdx
- 060-Rest-API/040-limits.mdx
Change transaction references to "single-call transactions", remove mentions of Beta.
Closes https://github.com/xataio/mdx-docs/issues/255
> Move transaction docs to GA

- 020-Getting-started/030-Framework-starter-guides/010-astro.mdx
Closes #
- Just a few typo fixes, no content changed :) 
---
> Fixing a few typos in Get started with Astro and Xata

- 030-Concepts/030-data-model.mdx
Add notes about limitations with backwards links.
> add revlink limitations

- 040-SDK/150-file-attachments.mdx
- 060-Rest-API/040-limits.mdx
Had a go at rewriting this docs page.
> File attachments SDK improvements

- 040-SDK/150-file-attachments.mdx
- 060-Rest-API/040-limits.mdx
Follows up: https://github.com/xataio/mdx-docs/pull/266/files
> Sdk file attachment follow ups

- 080-Recipes/040-workflow.mdx
Explicitly mention GH PR revert is not possible.
> add warning about reverts

- 020-Connect/030-Python/010-overview.mdx
follow up of https://github.com/xataio/mdx-docs/pull/275
> Formatting fixes for Python SDK

- 010-Getting-started/010-what-is-xata.mdx
- 040-Data-operations/111-search.mdx
- 040-Data-operations/111-vector-search.mdx
- 040-Data-operations/120-aggregate.mdx
- 040-Data-operations/140-ask.mdx
- 040-Data-operations/150-file-attachments.mdx
- 100-Appendix/030-limits.mdx
Adjust docs about optional Search store.
Closes https://github.com/xataio/mdx-docs/issues/270
> Docs for search opt-out

- 070-Integrations/010-airbyte.mdx
> Mark Airbyte integration as alpha

- 070-Integrations/010-airbyte.mdx
> Mark Airbyte as beta

- 070-Integrations/065-oauth.mdx
Very small PR that fixes an ugly bug. Auto-merges on approval
> Oauth page missing code block lang

- 030-Data-types/030-data-model.mdx
Update file data type names in data model.
> Update file data type names in data model.

- 100-Appendix/025-sla.mdx
Adds a SLA page against the #281 PR. Opened as a separate PR for easier review.
> Added an SLA page

- 020-Connect/070-Rust/010-sqlx.mdx
Link to the relevant section in the preview: 
https://xata-docs-pr-310.vercel.app/docs/rust-sqlx
> Add rust sqlx connect example

- 050-Manage/010-dedicated-cluster.mdx
Ads more info and flips published to true.
> Updated the dedicated cluster page

- 050-Manage/050-usage-metrics.mdx
follow up of https://github.com/xataio/mdx-docs/pull/305
> [Merge Wednesday] Publish usage metrics docs

- 020-Connect/010-Postgres/001-direct-access.mdx
add more types and functions to the supported statements in a shared cluster
> More supported types

- 020-Connect/020-JavaScript/030-drizzle.mdx
Document limitations from: https://github.com/xataio/xata/issues/4346
> Drizzle limitation for references and anonymous code blocks

- 020-Connect/030-Python/010-xata-sdk.mdx
- missing client init
- self. reference removed
> Fix Python pagination code snippet

- 010-Getting-started/030-Framework-starter-guides/040-remix.mdx
Remix on Vercel doesn't pick up the fetch implementation.
From: https://discord.com/channels/996791218879086662/1219884837502980168/1226394984727449740
> fetch remarks for remix

- 020-Connect/010-Postgres/001-direct-access.mdx
- 050-Manage/010-dedicated-cluster.mdx
co-locate temp table and table actions.
> Move temp table up

- 070-Integrations/060-netlify.mdx
Document findings reported in https://github.com/xataio/client-ts/issues/1437
> netlify edge docs

- 020-Connect/015-CLI/010-cli.mdx
Some clarifications and codegen flag for non interactive use of xata init
> add codegen flag and env vars for non interactive

- 050-Manage/050-usage-metrics.mdx
Metrics are now available at the branch level. 
Minor docs corrections to reflect this.
> Usage Metrics Branch updates

- 010-Getting-started/030-Framework-starter-guides/010-astro.mdx
Matches https://github.com/xataio/examples/pull/977
> Astro config set to server instead of hybrid

- 020-Connect/010-Postgres/001-direct-access.mdx
> Add VACUUM as unsupported statement

- 020-Connect/050-PHP/020-Laravel.mdx
> Enable Laravel connection guide

- .github/workflows/lint.yml
- .github/workflows/prettier-fixes.yml
Stealing the work of @exekias in the xata repo: https://github.com/xataio/xata/pull/4931
> Update pnpm action to v4

- 100-Appendix/020-pricing.mdx
- 100-Appendix/035-inactivity.mdx
- what effect does an inactive branch have in my workspace
- describe the duration and events for a branch to become inactive
> Inactive branches

- 020-Connect/010-Postgres/001-direct-access.mdx
- 050-Manage/010-dedicated-cluster.mdx
- change stability to beta
- add supported regions verbatim
- moving of branches
- termination protections
https://xata-docs-pr-343.vercel.app/docs/dedicated-cluster
> [DO NOT MERGE] Dedicated clusters, new regions and stability

- 020-Connect/010-Postgres/001-direct-access.mdx
- 050-Manage/010-dedicated-cluster.mdx
- list all extensions directly with SQL result: https://xata-docs-pr-365.vercel.app/docs/dedicated-cluster#extensions
- add postgis to OOTB installed: https://xata-docs-pr-365.vercel.app/docs/postgres#extensions
> SQL Extensions

- 050-Manage/030-migrations.mdx
Updating the link based on some wonderful feedback in Discord 😄
> migration blog link fix

- 010-Getting-started/010-what-is-xata.mdx
- 010-Getting-started/030-Framework-starter-guides/010-astro.mdx
- 010-Getting-started/030-Framework-starter-guides/030-nuxt.mdx
- 010-Getting-started/030-Framework-starter-guides/040-remix.mdx
- 020-Connect/015-CLI/010-cli.mdx
- 020-Connect/030-Python/010-xata-sdk.mdx
- 020-Connect/030-Python/120-pg8000.mdx
- 050-Manage/040-pr-based-workflow.mdx
- 070-Integrations/005-csv.mdx
- 070-Integrations/010-airbyte.mdx
Docs for https://github.com/xataio/client-ts/pull/1542
Piggybacked some typofixes that I found along the way (using cspell)
> feat(migrate): docs

- 030-Data-types/030-data-model.mdx
- 040-Data-operations/101-get.mdx
- 040-Data-operations/120-aggregate.mdx
- 040-Data-operations/150-file-attachments.mdx
- 040-Data-operations/160-image-transformations.mdx
- 100-Appendix/030-limits.mdx
Adjust docs for UI changes:
- string replaced by text
- multiple replaced by text[]
- datetime replaced by timestamptz
- deprecation of email type
> Adjust docs for column type updates

- 010-Getting-started/010-what-is-xata.mdx
- 100-Appendix/030-limits.mdx
I think I got all the references in the docs
https://github.com/search?q=repo%3Axataio%2Fmdx-docs%201%20gb&type=code
Slack thread: https://xata-hq.slack.com/archives/C03ELB1L1T6/p1726663690733049?thread_ts=1726491846.924629&cid=C03ELB1L1T6
> File limits: change 1gb to 5gb

- 020-Connect/099-REST/001-rest-api.mdx
- 030-Manage/040-pr-based-workflow.mdx
- 040-SDK/100-installation.mdx
- 100-Appendix/080-Data-types/030-data-model.mdx
Also did some light editing on a page to differentiate xata lite from the current product.
> Fix some broken links in docs
