xataio/mdx-docs

060-Rest-API/030-openapi.mdx
Because of how the APIs are now generated from root, we needed to move the location of the open API spec. Once https://github.com/xataio/website/pull/497 is merged, this PR should merge to account for the change.
=> Fix open API reference

030-Concepts/020-how-it-works.mdx, 030-Concepts/030-data-model.mdx, 030-Concepts/050-schema.mdx, 040-Typescript-SDK/030-create.mdx, 040-Typescript-SDK/040-get.mdx, 040-Typescript-SDK/050-filtering.mdx
Some of the changes made to docs to highlight the [object deprecation](https://xata.io/docs/concepts/data-model#object) did not make it into the new repo. This PR adds these unsync'ed bits.
**Release**:
=> Sync changes after relaunch

050-Python-SDK/040-namespace-reference.mdx
Fix minor typo on the python SDK nav
Closes #
- Change`referneces` -> `references` in the navTitle
---
**Release**:
=> Correct typo on 040-namespace-reference.mdx

050-Python-SDK/020-examples.mdx
Added `search_and_filter().queryTable()` example to Python examples.
Closes #
Added a python example of how to use the search_and_filter functionality to query a table.
---
**Release**:
=> Added `search_and_filter().queryTable()` example to Python docs examples

040-Typescript-SDK/050-filtering.mdx
Using `xata.createdAt` in filter context without quotes hits a PARSE_ERROR.
This updates the relevant docs example.
Reported on [Discord](https://discord.com/channels/996791218879086662/996791219348852836/1135793039986659408)
=> Quote xata.createdAt

030-Concepts/030-data-model.mdx
Removing the table parameter, which causes `"message": "invalid key [table] in request"`.
=> Fix relation query example

.github/workflows/preview.yml
https://github.com/xataio/mdx-docs/actions/runs/5948723525/job/16133075036?pr=62
I think this is happening because vercel is configured for 2 concurrent builds, so often we're waiting 10mins for this vercel deploy to happen but the github action is configured for 5 mins.
=> Adjust timeout for preview action

030-Concepts/075-file-attachments.mdx
Can't have a tabbed code block with one tab.
=> Fix tab block in file attachments

020-Getting-started/070-nextjs.mdx, 020-Getting-started/080-astro.mdx, 020-Getting-started/090-remix.mdx, 020-Getting-started/100-sveltekit.mdx, 020-Getting-started/110-solidstart.mdx
Required following https://github.com/xataio/examples/issues/548
- Updates the `<main />` element in the getting started guides to fix the above referenced layout issue
- Moves duplicate code (also `<main />` and some other header elements) into a layout file in Next.js example
- Some Astro & Remix updates based on auto-formatting changes
---
**Release**:
=> Getting started layout updates

040-SDK/101-get.mdx, 040-SDK/102-create.mdx, 040-SDK/103-update.mdx, 040-SDK/104-delete.mdx, 040-SDK/115-filtering.mdx, 040-SDK/121-summarize.mdx
This PR changes the existing SQL examples
to use parameterized queries to submit
query parameters.
Hopefully, this helps users avoid SQL injection
errors if we provide secure examples.
=> Use parameterized queries in SQL examples

040-SDK/010-TypeScript/010-overview.mdx
Document known limitation about type recursion from https://github.com/xataio/client-ts/issues/1221
=> add SDK limitation section with type recursion

030-Concepts/075-file-attachments.mdx
Suggestion from a user on our Discord to make the on-demand nature of signed URLs more explicit in our documentation.
=> Be more explicit about fetching a signed URL

060-Rest-API/040-limits.mdx
rate limiting URL was pointing to an old docs page.
**Release**:
=> Fix pricing docs URL

.github/workflows/preview.yml, 060-Rest-API/020-contexts.mdx
Add a hint for configuring Postman authentication with Bearer Token.
This is not clear by default, so users tend to select the API Key method in Postman instead which does not prepend "Bearer" before the Xata API Key, resulting in auth error.
=> clarify Postman Bearer Token

020-Getting-started/040-workflow.mdx
Clarifies that branch migrations and data copy are applied by forking the `main` branch.
The intention is to avoid misunderstanding, in case a PR is issued against a branch other than main.
---
Merge on approval
=> Clarify main branch  in Workflow

040-SDK/111-search.mdx
Add totalCount example updates
=> Update docs for search change

040-SDK/150-file-attachments.mdx
This has come up a few times so needs to be clarified in docs: users are concerned when they don't get the file content when expanding with wildcard (`filecolumn.*`)
This clarifies the `base64Content` is not returned when selecting columns with wildcard and it needs to be called explicitly.
=> clarify retrieving base64Content

030-Concepts/050-schema.mdx, 030-Concepts/075-file-attachments.mdx, 080-Recipes/020-create-schema-from-code.mdx
Provides examples that show how to make file columns public by default. Related to https://github.com/xataio/client-ts/pull/1281
=> Document public file columns in schema

040-SDK/150-file-attachments.mdx
An additional reference for how to get file content and signed urls as users continue to step on this.
=> Clarify selecting base64Content and signedUrl

040-SDK/101-get.mdx
Adds a reference for sorting by nested json keys. This is currently not possible in the REST API but is supported with the SQL proxy.
=> add sorting nested json example

030-Concepts/075-file-attachments.mdx
Closes #
The https://github.com/xataio/xata-go/releases/tag/v0.0.3 release introduced the upload URL TTL  property. Adding the example snippet.
**Release**:
=> Add code snippet for UploadUrl in xata-go

040-SDK/010-TypeScript/010-overview.mdx
The example was missing the async and await bits.
=> Fix serialization example in TS overview

040-SDK/135-sql-access.mdx
Closes #181 
- **Add unsupported commands** - Add  `upsert` and `sequence` to table of SQL commands not supported
---
---
**Release**:
=> Adding unsupported commands

020-Getting-started/020-installation.mdx
PR https://github.com/xataio/mdx-docs/pull/217 introduced an incorrect way to initialize the Go SDK.
=> Fix Go SDK (follow up from #217)

040-SDK/130-transaction.mdx
Another instance of `xata.records().transactions` instead of `transaction`.
=> Python snippet transaction trailing s

060-Rest-API/040-limits.mdx
The concurrency rates were leftover from the units era, this PR adjusts them to the current tiers.
=> add tier concurrency info

020-Getting-started/030-Framework-starter-guides/010-astro.mdx, 020-Getting-started/030-Framework-starter-guides/020-nextjs.mdx, 020-Getting-started/030-Framework-starter-guides/030-nuxt.mdx, 020-Getting-started/030-Framework-starter-guides/040-remix.mdx, 020-Getting-started/030-Framework-starter-guides/050-sveltekit.mdx, 020-Getting-started/030-Framework-starter-guides/060-solidstart.mdx, 060-Rest-API/020-contexts.mdx, 080-Recipes/010-CSV-data/020-import-csv-data-CLI.mdx
Updates existing references to workspace name and id to use a consistent example `my-workspace-123456`. We should strive to reuse this for any future examples of workspace name and id in the docs. 
---
**Release**:
=> chore: consolidate example workspace id

040-SDK/150-file-attachments.mdx
Why?
Record API is used for more than just uploads. You do actually want to use records for things other than uploading files. The summary / top of this page made it seem like Record APIs were used for uploads only, which isn't the case.
=> Slant of Richard's file upload work

030-Concepts/030-data-model.mdx, 040-SDK/101-get.mdx
Add docs warnings about lack of json sorting to make the known limitation standout.
Closes #https://github.com/xataio/mdx-docs/issues/256
=> add warnings about json sorting

040-SDK/111-search.mdx, 040-SDK/120-aggregate.mdx
Declares aggregations as experimental and adds known issues.
Closes https://github.com/xataio/mdx-docs/issues/254
=> declare aggregate as experimental

.eslintrc.js, package.json, pnpm-lock.yaml
Problem:
`﻿node_modules/.bin/eslint --fix 040-SDK/150-file-attachments.mdx` completely messes up the formatting of that file.
Solution: 
?
I've turned off `--fix` on commit hook, which I think ~should be fine and stop people running to problems.
=> Lint: Not auto `eslint --fix` on commit hooks

010-Getting-started/030-Framework-starter-guides/010-astro.mdx, 010-Getting-started/030-Framework-starter-guides/020-nextjs.mdx, 010-Getting-started/030-Framework-starter-guides/030-nuxt.mdx, 010-Getting-started/030-Framework-starter-guides/040-remix.mdx, 010-Getting-started/030-Framework-starter-guides/050-sveltekit.mdx, 010-Getting-started/030-Framework-starter-guides/060-solidstart.mdx
Noticed the mp4 links were malformed on the GS pages. This was due to some folder name changes in the big reorg last week.
This is a small fix. I'll merge without review assuming green CI and a manual check of the build.
=> Fix broken mp4 links

040-Data-operations/101-get.mdx
Missing call out to show how to select a database in the xata-go SDK for the Query API.
=> Add missing database name reference

040-Data-operations/150-file-attachments.mdx
Clarifies setting metadata for files uploaded via binary API.
=> add reference for updating binary uploads with record API

030-Data-types/030-data-model.mdx, 040-Data-operations/111-search.mdx
Document limitations due to JSON mapped as `text` in Search.
=> document json limitations in search

040-Data-operations/150-file-attachments.mdx
Add the new upload subdomain to support file uploads larger than 100mb.
=> add uploads url to rest api examples

020-Connect/010-Postgres/010-sql-access.mdx
In TypeScript examples, when we don't expect a response, typing like this `xata.sql<UsersRecord>` was unnecessary, so I removed that to simplify. Also did a tiny change to the python example, because likewise we don't expect a list of records in the return.
=> Simplify SQL examples

040-Data-operations/120-aggregate.mdx, readme.md
Fixes https://github.com/xataio/frontend-next/issues/3123
Added some documentation. The alert component typically assumes simple strings. You can get more verbose with some whitespace.
=> Alert component documentation and fixes for complicated markup

020-Connect/010-Postgres/001-direct-access.mdx
Describe how Xata uses metadata comments on columns and a warning not to change/remove them when adding your own comments.
Direct link to the new section in the preview: https://xata-docs-pr-308.vercel.app/docs/postgres#column-metadata
=> Add a `Connect to Postgres/Column metadata` section about column comments

040-Data-operations/120-aggregate.mdx
The aggregation syntax used in the intro sections for aggregations was invalid.
=> fix aggregation examples

030-Data-types/030-data-model.mdx
The `json` column type was missing from the Xata types summary.
=> add json to xata types table

040-Data-operations/150-file-attachments.mdx
closes #330 
missing the TS part, pinging @SferaDev
=> Document the content type header for the files API

.gitignore, 010-Getting-started/030-Framework-starter-guides/010-astro.mdx
Added a deployment explanation for the framework starter guide for Astro. That explains the adding of a ssr adapter for deployment use. Of a Astro Xata blog, from the starter guide. Also fixed a typo with the naming of a component from src/app/page.tsx to src/pages/index.astro. To help with confusion of naming components or where said code should go while adding the search functionality to the app.
=> Added deployment explanation to docs for the framework starter guide for Astro

.gitignore, 010-Getting-started/030-Framework-starter-guides/010-astro.mdx
Move over https://github.com/xataio/mdx-docs/pull/329 from fork to have a preview available.
=> Added deployment explanation to docs for the framework starter guide

040-Data-operations/111-search.mdx
Add a note regarding search behaviour with records that are too large.
Relates to #4583
=> Add record size limitation to search docs

020-Connect/010-Postgres/001-direct-access.mdx
Adds sslmode require option in all examples, even if it's redundant for psql which defaults to it.
The connection string requires this option to work with other clients and ORMs (i.e. Drizzle) and it's hard for a user to notice the difference, so it's best to promote syntax that covers more uses.
From user feedback on [Discord](https://discord.com/channels/996791218879086662/996791219348852836/1245718350479233046).
=> add ssl require option to postgres docs

050-Manage/040-pr-based-workflow.mdx
Add a point at the top of limitations to clarify the data copy destination branch.
=> clarify data copy target branch

030-Data-types/030-data-model.mdx
Because of the issue [5xx when column doesn't exist on query endpoint](https://github.com/xataio/xata/issues/3729), the docs example query doesn't work, as it is not selecting the createdAt column.
Also, due to [5xx from reverse link sorting on xata metadata](https://github.com/xataio/xata/issues/3738), adding a clarification that createdAt refers to another column, not the xata default one. Users often try to use the xata internal columns for sorting, which errors. These do work with pg databases though.
=> fix rev link sorting query

050-Manage/040-pr-based-workflow.mdx, 070-Integrations/030-github.mdx
Users of postgres-enabled databases have been trying to use the gh integration and workflow, which don't work while branch merging isn't possible with pg branches.
=> add workflow warnings for pg branches

040-Data-operations/150-file-attachments.mdx
A user pointed out that the file name restrictions for file attachments are quite specific but not referenced in docs. This clarifies the valid character set for file names in the Records API.
=> file name restrictions

040-Data-operations/121-summarize.mdx
- Fix incorrect call syntax for columns in summarize snippets
- Rephrase suggestion to using Aggregate as a "no result limits" endpoint as it is not true for every call. For example, a common case for users trying out aggregate is the 1000 result buckets of Summarize, which still applies in Aggregate's [top values](https://xata.io/docs/sdk/aggregate#top-values). This avoids setting expectations that can't be met in every case.
=> Fixes for summarize and aggregate docs

020-Connect/010-Postgres/001-direct-access.mdx
This PR adds `pgvector`, `pgcrypto` and `uuid-ossp` to the
list of supported extensions on shared clusters.
=> Update the list of supported extensions on shared clusters

020-Connect/010-Postgres/001-direct-access.mdx
This PR adds a note about the default branch in the connection string.
If the user does not specify a branch name, we connect them to their
`main` branch.
=> Add note about default database branch in PostgreSQL connection string

.github/workflows/lint.yml, .github/workflows/prettier-fixes.yml, 020-Connect/010-Postgres/001-direct-access.mdx, 020-Connect/020-JavaScript/020-prisma.mdx
Clarifications about prisma db pull and the shadow db.
=> Prisma docs updates

020-Connect/010-Postgres/001-direct-access.mdx, pnpm-lock.yaml
This PR changes to the links of extensions in shared clusters.
From now on, they point to the version of the installed extension.
In case of `ossp-uuid`, `pgcrypto` and `plpgsql`, the links point to PostgreSQL 15
pages. In case of `pgvector` it points to the v0.5.0 (ref: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/AuroraPostgreSQL.Extensions.html#AuroraPostgreSQL.Extensions.15)
=> Change link to installed versions of extensions

020-Connect/010-Postgres/001-direct-access.mdx
`SELECT pg_reload_conf();` is not allowed
=> Add unsupported SQL statement

020-Connect/010-Postgres/001-direct-access.mdx
Closes https://github.com/xataio/xata/issues/4873
=> New statements added to permissions matrix, permissions updated

020-Connect/020-JavaScript/030-drizzle.mdx
Has been fixed a while ago: https://github.com/xataio/xata/issues/4346
=> Drizzle: remove bullet point about foreign key limitations

040-Data-operations/111-vector-search.mdx
This PR corrects the mislabelled `results` field and adds context about the location of the `id` and `score` fields in the Vector Search docs.
The docs describe the response from the `vectorSearch` function but it doesn't correspond to the actual response.
Here's the relevant section from the docs at https://xata.io/docs/sdk/vector-search:
> The response includes the following:
> 
> `totalCount`: The total number of records matching the query vector.
> `results`: An array of the most relevant records. Each item in `results` includes the `id` and `score`.
> `id`: A unique identifier for the record.
> `score`: A similarity score (usually between 0 and 1) indicating how closely the record's vector matches the query vector.
Here's an example of what is actually returned:
```js
{
records: [
{ …
```
=> Docs - Fix Mislabelled Field

010-Getting-started/020-installation.mdx
Reported in Discord: https://discord.com/channels/996791218879086662/996791219348852836/1277769977893621901
The docs were discussing a `src/client.ts` file, likely meaning the `src/xata.ts` file. I also changed a bit the wording of the paragraph, I think it's easier to understand this way.
=> Fix typo and wording around the client.ts file
